version: "3.7"

services:
  api:
    image: python_api_with_metrics-api:latest
    build: app/.
    deploy:
      replicas: 3
    ports:
      - "9091:9091"
    environment:
      - PROMETHEUS_DISABLE_CREATED_SERIES=True
    networks:
      - myapi

  prometheus:
    image: python_api_with_metrics-prometheus:latest
    build: prometheus/.
    deploy:
      replicas: 1
    ports:
      - "9090:9090"
    networks:
      - myapi

  grafana:
    image: python_api_with_metrics-grafana:latest
    build: grafana/.
    deploy:
      replicas: 1
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - myapi



networks:
  myapi:
    name: my-api-network