global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "api"
    metrics_path: "/"
    dns_sd_configs:
      - names:
          - tasks.api
        type: A
        port: 8000
        refresh_interval: 5s
    metric_relabel_configs:
      - action: labeldrop
        regex: exported_instance